instagram_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('test_app.urls'))
]

test_app/urls.py
from django.conf.urls import url

from . import views

app_name = 'test_app'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^authorized/$', views.authorized, name='authorized'),
    url(r'^viewDestinations/$', views.view_destinations, name='view_destinations'),
    url(r'^viewPhotos/(?P<destination_id>[0-9]+)/(?P<destination_name>[\w\- ]+)/?', views.view_photos, name='view_photos')
]

test_app/models.py
from django.db import models

# Create your models here.

test_app/forms.py
from django import forms

class DestinationSelectionForm(forms.Form):
    destination_name = forms.CharField(label='Destination')

test_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
import os, requests
from test_app.instagramCredentials import InstagramCredentials
from test_app.retrieveInstagramData import RetrieveInstagramData
from test_app import constants
from test_app.forms import DestinationSelectionForm

def home(request):
    uri = os.path.join(request.build_absolute_uri(), 'authorized/')
    request.session[constants.REDIRECT_URI] = uri
    url = 'https://api.instagram.com/oauth/authorize/?client_id='
    url += constants.CLIENT_ID + '&redirect_uri=' + uri + '&response_type=code&scope=public_content'
    return HttpResponseRedirect(url)

def authorized(request):
    ig_credentials = InstagramCredentials()
    if constants.ACCESS_TOKEN not in request.session:
        ig_credentials.set_access_token(request)
    return HttpResponseRedirect('/viewDestinations/')

def view_destinations(request):
    retriever = RetrieveInstagramData()
    context = {}
    # if the user entered text, populate the dropdown with completed destination options
    # for them to select from
    if request.method == constants.POST:
        form = DestinationSelectionForm(request.POST)
        if form.is_valid():
            context = retriever.get_destination_list(request, form.cleaned_data[constants.DESTINATION_NAME])
            request.session[constants.DESTINATION_NAME] = form.cleaned_data[constants.DESTINATION_NAME]
    else:
        form = DestinationSelectionForm()
    context[constants.FORM] = form

    return render(request, 'test_app/viewDestinations.html', context)

def view_photos(request, destination_id, destination_name):
    if constants.DESTINATION_NAME in request.session:
        name = request.session[constants.DESTINATION_NAME]
    else:
        name = ''
    retriever = RetrieveInstagramData()
    context = retriever.get_photos(request, destination_name, destination_id)
    form = DestinationSelectionForm({constants.DESTINATION_NAME: name})
    context[constants.FORM] = form

    return render(request, 'test_app/viewDestinations.html', context)

test_app/templates/test_app/authorized.html
<!-- <h1>View Destination Photos</h1>
<form>
	<label>Destination</label>
	<input type="text" />
</form> -->

{% if data %}
<h1>{{destination}}</h1>
{% for item in data %}
	<img src={{item.images.thumbnail.url}}>
{% endfor %}
{% else %}
<h1>No Results Available For {{destination}}</h1>
{% endif %}

test_app/templates/test_app/viewDestinations.html
<h1>View Destination Photos</h1>
<form action='/viewDestinations/' method='post'>
    {% csrf_token %}
    {{form}}
    <input type='submit' value='Search' />
</form>

{% if destination_list %}
    <div name='destination'>
        {% for item in destination_list %}
            <a href="{% url 'test_app:view_photos' item.id item.name %}">{{item.name}}</a>
            <br />
        {% endfor %}
    </div>
{% endif %}

{% if images %}
    <h1>{{destination}}</h1>
    {% for item in images %}
        <img src={{item.images.thumbnail.url}}>
    {% endfor %}
{% endif %}